[package]
name = "sakuya"
version = "0.1.0"
description = "A game in the making!"
edition = "2024"
license-file = "LICENSE"
readme = "README.md"

[dependencies]
bevy = "0.17"
bevy-inspector-egui = "0.35.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
